### ISSUE TITLE
Fatal checking the current user is instructor of Certificate or Achievement

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1064]
### Reproduction Steps

Cannot reproduce it, customers haven't provided with reproduction steps yet

### Expected Behavior

+ no PHP error logged/reported

### Actual Behavior

+ PHP error logged/reported

### Error Messages / Logs

site 1:
```
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.3.2
Current theme: LifterLMS LaunchPad Child (version 1.1.0)
Current plugin: Query Monitor (version 3.5.2)
PHP version 7.2.25-1+ubuntu18.04.1+deb.sury.org+1

Error message: Uncaught Error: Call to undefined method LLMS_Achievement::get() in /var/www/{redacted1}/htdocs/wp-content/plugins/lifterlms/includes/llms.functions.core.php:808
Stack trace:
#0 /var/www/{redacted1}/htdocs/wp-content/plugins/lifterlms/includes/models/model.llms.instructor.php(297): llms_get_post_parent_course(Object(LLMS_Achievement))
#1 /var/www/{redacted1}/htdocs/wp-content/plugins/lifterlms/includes/class.llms.user.permissions.php(97): LLMS_Instructor->is_instructor('339')
#2 /var/www/{redacted1}/htdocs/wp-content/plugins/lifterlms/includes/class.llms.user.permissions.php(162): LLMS_User_Permissions->edit_others_lms_content(Array, Array, Array)
#3 /var/www/{redacted1}/htdocs/wp-includes/class-wp-hook.php(290): LLMS_User_Permissions->handle_caps(Array, Array, Array)
#4 /var/www/{redacted1}/htdocs/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#5 /var/www/{redacted1}/htdocs/wp-includes/
```

site 2:
```
Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, LifterLMS.

First, visit your website (https://{redacted2}.com/) and check for any visible issues. Next, visit the page where the error was caught (https://{redacted2}.com/wp-admin/) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://{redacted2}.com/wp-login.php?action=enter_recovery_mode&rm_token=

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.3.2
Current theme: X - Child Theme (version 1.0.0)
Current plugin: LifterLMS (version 3.37.13)
PHP version 7.3.13


Error Details
=============
An error of type E_ERROR was caused in line 808 of the file /home1/{redacted2}/public_html/wp-content/plugins/lifterlms/includes/llms.functions.core.php. Error message: Uncaught Error: Call to undefined method LLMS_Certificate::get() in /home1/{redacted2}/public_html/wp-content/plugins/lifterlms/includes/llms.functions.core.php:808
Stack trace:
#0 /home1/{redacted2}/public_html/wp-content/plugins/lifterlms/includes/models/model.llms.instructor.php(297): llms_get_post_parent_course(Object(LLMS_Certificate))
#1 /home1/{redacted2}/public_html/wp-content/plugins/lifterlms/includes/class.llms.user.permissions.php(97): LLMS_Instructor->is_instructor('719')
#2 /home1/{redacted2}/public_html/wp-content/plugins/lifterlms/includes/class.llms.user.permissions.php(162): LLMS_User_Permissions->edit_others_lms_content(Array, Array, Array)
#3 /home1/{redacted2}/public_html/wp-includes/class-wp-hook.php(290): LLMS_User_Permissions->handle_caps(Array, Array, Array)
#4 /home1/{redacted2}/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#5 /home1/{redacted2}/public_html/wp-includes/class-wp-user.php(780): apply_filters('user_has_cap', Array, Array, Array, Object(WP_User))
#6 /home1/
```

### System Information
site 1:
<details>
<summary>System Report</summary>
  
```
Wordpress
-------------------------------------------

Home Url: https://{redacted1}.com
Site Url: https://{redacted1}.com
Login Url: https://{redacted1}.com/wp-login.php
Version: 5.3.2
Debug Mode: Yes
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Welcome (#303) [https://{redacted1}.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.37.13
Db Version: 3.37.13
Course Catalog: Course Catalog (#6) [https://{redacted1}.com/courses/]
Membership Catalog: Membership Catalog (#7) [https://{redacted1}.com/memberships/]
Student Dashboard: Dashboard (#9) [https://{redacted1}.com/dashboard/]
Checkout Page: Purchase (#8) [https://{redacted1}.com/purchase/]
Course Catalog Per Page: 12
Course Catalog Sorting: title,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint:
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: medium
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: CA
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: {redacted}@{redacted}.com
Email From Name: {redacted1}.com
Email Footer Text:
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Authorize.Net: Disabled
Authorize.Net Test Mode: Disabled
Authorize.Net Logging:
Authorize.Net Order: 1
PayPal: Disabled
PayPal Test Mode: Disabled
PayPal Logging:
PayPal Order: 1
Stripe: Disabled
Stripe Test Mode: Disabled
Stripe Logging:
Stripe Order: 1
Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 8.0.17
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 512M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 600
Php Version: 7.2.25-1+ubuntu18.04.1+deb.sury.org+1
Software: nginx/1.16.1
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36


Theme
-------------------------------------------

Name: LifterLMS LaunchPad Child
Version: 1.1.0
Themeuri: https://lifterlms.com/product/launchpad/
Authoruri: https://lifterlms.com
Template: lifterlms-launchpad
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Admin Custom Login: 3.1.5
Disable Emojis (GDPR friendly): 1.7.2
Gravity Forms: 2.4.17
Gravity Forms Survey Add-On: 3.4
Gravity Forms User Registration Add-On: 4.4
GridPane Redis Object Cache: 1.5.5
H5P xAPI: 0.1.6
JSM's Show User Metadata: 1.1.0
LifterLMS: 3.37.13
LifterLMS Advanced Quizzes: 1.0.10
LifterLMS Assignments: 1.1.6
LifterLMS Authorize.Net Payment Gateway: 1.0.5
LifterLMS Customizations: 1.0.0
LifterLMS Gravity Forms: 2.0.1
LifterLMS Helper: 3.0.2
LifterLMS Labs: 1.5.3
LifterLMS MailChimp Add-on: 3.1.2
LifterLMS PayPal Gateway: 1.2.0
LifterLMS Private Areas: 1.1.1
LifterLMS Social Learning: 1.2.1
LifterLMS Stripe Payment Gateway: 5.2.0
LifterLMS xAPI: 1.3.0.1
Nginx Helper: 2.2.1
Query Monitor: 3.5.2
Really Simple SSL: 3.2.9
Responsive Lightbox: 1.3.3
SendWP: 1.0.2
UpdraftPlus - Backup/Restore: 1.16.22
User Role Editor: 4.53
WordPress Backup & Security Plugin - BlogVault: 3.4
WordPress User Notes: 1.2.2
WP Awesome Import & Export: 3.2.1
WPFront Notification Bar: 1.7.1
WP Security Audit Log: 4.0.2


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS Gravity Forms: Yes
LifterLMS MailChimp: No
LifterLMS Private Areas: No
LifterLMS Social Learning: Yes


Template Overrides
-------------------------------------------

```

</details>

site 2:
<details>
<summary>System Report</summary>
  
```
Wordpress
-------------------------------------------

Home Url: https://{redacted2}.com
Site Url: https://{redacted2}.com
Login Url: https://{redacted2}.com/wp-login.php
Version: 5.3.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Inspiration (#116) [https://{redacted2}.com/inspiration/]
Page On Front: 40 Days of Focus (#125) [https://{redacted2}.com/]
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.37.13
Db Version: 3.37.13
Course Catalog: Course Catalog (#271) [https://{redacted2}.com/courses/]
Membership Catalog: Not Set
Student Dashboard: My Courses (#274) [https://{redacted2}.com/my-courses/]
Checkout Page: Purchase (#273) [https://{redacted2}.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: weak
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: yes
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: support@{redacted2}.com
Email From Name: 40 Days of Focus
Email Footer Text: 
Email Header Image: 152
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: yes
Stripe Order: 1
Manual: Disabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.6.41
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 512 MB
Php Memory Limit: 512M
Php Post Max Size: 512M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 3000
Php Version: 7.3.13
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0


Theme
-------------------------------------------

Name: X – Child Theme
Version: 1.0.0
Themeuri: http://theme.co/x/
Authoruri: http://theme.co/
Template: x
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

BuddyBoss Platform: 1.2.8
Cornerstone: 4.2.2
Easy Forms for Mailchimp: 6.6.3
Gutenberg: 7.7.1
Jetpack by WordPress.com: 8.3
LifterLMS: 3.37.13
LifterLMS Advanced Videos: 1.0.0-beta.8
LifterLMS Helper: 3.0.2
LifterLMS Labs: 1.5.3
LifterLMS MailChimp Add-on: 3.1.2
LifterLMS Private Areas: 1.1.1
LifterLMS Stripe Payment Gateway: 5.2.0
User Switching: 1.5.4
Wordfence Security: 7.4.6
WordPress User Notes: 1.2.2
WP Staging: 2.6.8
X – Google Analytics: 1.0.3


Integrations
-------------------------------------------

BbPress: No
BuddyPress: Yes
LifterLMS MailChimp: Yes
LifterLMS Private Areas: Yes
Videos: Vimeo: No
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------

```

</details>

### Browser, Device, and Operating System Information

n/a

### Related User Information

site 1: HS-114322
site 2: HS-114241

**Comment by eri-trabiccolo** [comment]
of course we can fix it even without reproduction steps, but I wonder what is producing this error...

**Comment by toyinogunseinde** [comment]
Also reported in HS-114483
