### ISSUE TITLE
Fatal on a WP_Users_List_Table when not in wp-admin/users.php

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#1297]
### Reproduction Steps

I'm able to reproduce this on a multisite install (I know we're not officially supporting ms), on an admin page like:
http://multisite.test/wp-admin/network/site-users.php?id=1

But it could happen with whatever `WP_Users_List_Table` instantiated (extended?) on a `$screen->id` different than 'users':
https://github.com/gocodebox/lifterlms/blob/4.3.3/includes/admin/class-llms-admin-users-table.php#L153
The thing is that we attempt to use a class whose file might even be not be required.
I think we could always require`LLMS_PLUGIN_DIR . 'includes/admin/reporting/class.llms.admin.reporting.php'`.

This has been reported by two customers at the moment, and for one of them, the only one who provided a real error report, the issue seems to be happened on the iTheme Security Pro plug-in settings page.

### Expected Behavior

+ No error

### Actual Behavior

+ Fatal raised

### Error Messages / Logs

```
First, visit your website (https://removed.guide/) and check for any visible issues. Next, visit the page where the error was caught (https://removed.guide/wp-admin/admin.php?page=itsec) and check for any visible issues.

Error Details
=============
An error of type E_ERROR was caused in line 66 of the file /srv/users/removed/apps/removed/public/wp-content/plugins/lifterlms/includes/admin/class-llms-admin-users-table.php. Error message: Uncaught Error: Class 'LLMS_Admin_Reporting' not found in /srv/users/removed/apps/removed/public/wp-content/plugins/lifterlms/includes/admin/class-llms-admin-users-table.php:66
Stack trace:
#0 /srv/users/removed/apps/removed/public/wp-includes/class-wp-hook.php(287): LLMS_Admin_Users_Table->add_actions(Array, Object(WP_User))
#1 /srv/users/removed/apps/removed/public/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#2 /srv/users/removed/apps/removed/public/wp-admin/includes/class-wp-users-list-table.php(483): apply_filters('user_row_action...', Array, Object(WP_User))
#3 /srv/users/removed/apps/removed/public/wp-admin/includes/class-wp-users-list-table.php(398): WP_Users_List_Table->single_row(Object(WP_User), '', '', 0)
#4 /srv/users/removed/apps/removed/public/wp-admin/includes/class-wp-list-table.php(1322): WP_Users_List_Table->display_rows()
#5 /srv/users/removed/apps/removed/public/wp-admin/includes/class-wp-list-table.php(1249): WP
```

### System and Environment Information

<details>
<summary>System Report 1</summary>

```
WordPress version 5.5
Current theme: Kadence (version 0.8.2)
Current plugin: LifterLMS (version 4.3.2)
PHP version 7.4.9
```

</details>

<details>
<summary>System Report 2</summary>

```
System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.5
Debug Mode: No
Debug Log: No
Debug Display: No
Locale: en_US
Multisite: Yes
Page For Posts: Blog (#264) [[removed]/blog/]
Page On Front: News Feed (#6) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.3.2
Db Version: 4.3.2
Course Catalog: Course Catalog (#1316) [[removed]/courses/]
Membership Catalog: Membership Catalog (#1317) [[removed]/memberships/]
Student Dashboard: Dashboard (#1319) [[removed]/dashboard/]
Checkout Page: Purchase (#1318) [[removed]/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: optional
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: optional
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: GR
Currency: EUR
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging:
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.31
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 5 MB
Php Memory Limit: 256M
Php Post Max Size: 512M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 600
Php Version: 7.4.8
Software: Apache/2.4.29 (Ubuntu)
Wp Memory Limit: 64M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36


Theme
-------------------------------------------

Name: BuddyBoss Child
Version: 1.0.0
Themeuri: https://www.buddyboss.com/
Authoruri: https://www.buddyboss.com/
Template: buddyboss-theme
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

BetterDocs: 1.3.4
BetterDocs Pro: 1.3.0
BigBlueButton: 3.0.0-beta.4
BLITZ - Admin UI PRO: 3.6
BLITZ - Rebrand [REMOVED] LMS PRO: 1.7
Branda Pro: 3.3.1
BuddyBoss Platform: 1.4.9
BuddyBoss Platform Pro: 1.0.2
BuddyPages: 1.1.0
BuddyPress Multi Network: 1.0.2
buyCRED Stripe: 2.2.6
Code Snippets: 2.14.0
H5P: 1.15.0
Insert Headers and Footers: 1.4.6
[REMOVED] LMS: 4.3.2
[REMOVED] LMS Advanced Quizzes: 1.0.10
[REMOVED] LMS Assignments: 1.1.9
[REMOVED] LMS Groups: 1.0.0-beta.8
[REMOVED] LMS Helper: 3.1.0
[REMOVED] LMS Private Areas: 1.1.2
Limit Groups per User: 2.0.2
Limit Login Attempts Reloaded: 2.15.1
Multisite Enhancements: 1.5.2
Multisite Toolbar Additions: 2.0.1
myCred: 1.8.12
Post SMTP: 2.0.15
Restrict Media Library Access: 1.0
Snapshot Pro: 4.0.2
The Events Calendar: 5.1.5
User Role Editor: 4.56
[REMOVED] Plugin:
WPMU DEV Dashboard: 4.9.4
WP Ultimo: 1.10.11
WP Ultimo: Admin Page Creator: 1.8.1
WP Ultimo: Multiple Accounts: 1.1.2
WP Ultimo: Plugin and Theme Manager: 1.2.5


Integrations
-------------------------------------------

BbPress: Yes
BuddyPress: Yes
LifterLMS Groups: Yes
[REMOVED] LMS Private Areas: Yes


Template Overrides
-------------------------------------------

content-certificate.php (ver: 3.18.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.18.0)
achievements/loop.php (ver: 3.14.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
achievements/template.php (ver: 3.14.6): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.6)
certificates/loop.php (ver: 3.14.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
certificates/preview.php (ver: 3.14.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
course/author.php (ver: 3.25.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.25.0)
course/lesson-preview.php (ver: 3.19.2): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.19.2)
course/syllabus.php (ver: 3.24.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.24.0)
loop/author.php (ver: 3.0.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.0.0)
loop/content.php (ver: 3.14.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
loop/featured-image.php (ver: 3.35.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
myaccount/dashboard-section.php (ver: 3.30.1): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.1)
myaccount/header.php (ver: 3.14.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
myaccount/my-grades-single-table.php (ver: 3.24.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.24.0)
myaccount/my-notifications.php (ver: 3.30.3): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.3)
myaccount/my-orders.php (ver: 3.17.6): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.6)
myaccount/view-order.php (ver: 3.35.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
product/access-plan-pricing.php (ver: 3.29.0): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.29.0)
quiz/results-attempt-questions-list.php (ver: 3.17.8): /var/www/removed/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.8)

```

</details>

###
This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User information
HS-131608
HS-131029

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

Thanks for the research.

The `load_dependencies()` method looks like it exists so that we don't have to run a dependency check on every row in the table in the `add_actions()` method where the error is actually being encountered.

**Comment by eri-trabiccolo** [comment]
@thomasplevy yeah, but the dependency loading is conditioned to something the `add_actions()` method doesn't care about.
The `add_actions()` method (as other methods in that class that want to use the dependency) is a filter callback, that you know better than me (**Oh, baby, baby, it's a wild world...**), can be called from anywhere, even from a totally different context than a user table.
Why don't we just require that file, as we use it only as _library_ (its class static methods), if we don't instantiate the class, and we don't, it won't be a big deal.
Am I missing anything? (totally possible, because **Oh, baby, baby, it's a wild world...**).

**Comment by thomasplevy** [comment]
> Why don't we just require that file, as we use it only as _library_ (its class static methods), if we don't instantiate the class, and we don't, it won't be a big deal.

Yea, you're right!

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm working on asset loading in #1292 and I'll rope this into that project.

**Comment by toyinogun** [comment]
HS-132387

**Comment by eri-trabiccolo** [comment]
HS-138390

**Comment by toyinogun** [comment]
HS-138434
