### ISSUE TITLE
Fatal error with a non-existing user in Single Student View: Courses Tab: Single Course View

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#1548]
I would be happy to fix this issue and submit a pull request. Please provide feedback on the preferred solution.
1. Have `LLMS_Student->get_grade()` check if user exists before getting the grade.
<details>
<summary>Code</summary>

```php
public function get_grade( $object_id, $use_cache = true ) {
	if ( $this->exists() ) {
		$grade = LLMS()->grades()->get_grade( $object_id, $this, $use_cache );
	} else {
		$grade = null;
	}
	if ( is_null( $grade ) ) {
		$grade = _x( 'N/A', 'Grade to display when no quizzes taken or available', 'lifterlms' );
	}
	return apply_filters( 'llms_student_get_grade', $grade, $this, $object_id, get_post_type( $object_id ) );
}
```
</details>

2. Have `LLMS_Grades->get_grade()` return null if student does not exist.
<details>
<summary>Code</summary>

```php
public function get_grade( $post_id, $student, $use_cache = true ) {

	$post    = llms_get_post( $post_id );
	$student = llms_get_student( $student );

	if ( $student->exists() ) {
		$grade = $use_cache ? $this->get_grade_from_cache( $post, $student ) : false;
	} else {
		$grade = null;
	}

	// Grade not found in cache or we're not using the cache.
	if ( false === $grade ) {

		$grade = $this->calculate_grade( $post, $student );

		// Store in the cache.
		wp_cache_set(
			sprintf( '%d_grade', $post->get( 'id' ) ),
			$grade,
			sprintf( 'student_%d', $student->get( 'id' ) )
		);

	}

	return apply_filters( 'llms_get_grade', $grade, $post, $student );

}
```
</details> 

3. Display a "student not found" error message. Would this be done in the `templates/admin/reporting/tabs/students/courses-course` file?

### Reproduction Steps

1. Go to LifterLMS Reporting.
2. Click on a user name.
3. Click on the "Courses" link that is next to "Information".
4. Click on a course name.
5. Change the `student_id` URL query variable value to a non-existing user.

This "bad" URL can occur with a bookmark created before a user is deleted, or by admins and LMS managers with fat fingers.

### Expected Behavior

I expected either a message that the user does not exist (or not found), or a report with empty values.

### Actual Behavior

> There has been a critical error on this website. Please check your site admin email inbox for instructions.

### Error Messages / Logs

```
PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in /WordPress/src/wp-content/plugins/lifterlms/includes/class-llms-grades.php:271
Stack trace:
#0 /WordPress/src/wp-content/plugins/lifterlms/includes/class-llms-grades.php(236): LLMS_Grades->get_grade_from_cache(Object(LLMS_Course), false)
#1 /WordPress/src/wp-content/plugins/lifterlms/includes/models/model.llms.student.php(755): LLMS_Grades->get_grade('5500', false, true)
#2 /WordPress/src/wp-content/plugins/lifterlms/templates/admin/reporting/tabs/students/courses-course.php(113): LLMS_Student->get_grade('5500')
#3 /WordPress/src/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('C://Vistacast//Wo...')
#4 /WordPress/src/wp-content/plugins/lifterlms/templates/admin/reporting/tabs/students/courses.php(55): llms_get_template('admin/reporting...', Array)
#5 /WordPress/src/wp-content/plugins/lifterlms/includes/functions/llms.functi in /WordPress/src/wp-content/plugins/lifterlms/includes/class-llms-grades.php on line 271
```

### System and Environment Information

LifterLMS 4.17.0

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://example.com
Site Url: https://example.com
Login Url: https://example.com/wp-login.php
Version: 5.6.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Dashboard (#8) [https://example.com/]
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show On Front: page
Wp Cron: No


Settings
-------------------------------------------

Version: 4.17.0
Db Version: 4.17.0
Course Catalog: Course Catalog (#5) [https://example.com/courses/]
Membership Catalog: Membership Catalog (#6) [https://example.com/memberships/]
Student Dashboard: Dashboard (#8) [https://example.com/]
Checkout Page: Purchase (#7) [https://example.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: info@example.com
Email From Name: Example
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 3000
Php Max Upload Size: 202 MB
Php Memory Limit: 328M
Php Post Max Size: 208M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.2.34
Software: Apache/2.4.6
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.0.3
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

Admin Columns Pro: 5.4.2
Admin Columns Pro - Meta Box: 1.1
Advanced Post Types Order: 4.3.8.6
Astra Pro: 3.0.1
CoolSys: 1.4.0
Experience Visualizer: 2.7.0
Fast User Switching: 1.4.9
Force Login: 5.5
H5P: 1.15.0
H5P xAPI: 0.1.6
LifterLMS: 4.17.0
LifterLMS Configurator: 2.0.3
LifterLMS xAPI: 1.3.0.1.1
OpenID Connect Generic: 3.8.1
Responsive Lightbox: 1.3.4
User Role Editor: 4.58.3
Wordfence Security: 7.4.14
WP Crontrol: 1.10.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------



```

</details>

This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Brave, Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)
+ Windows 10

**Comment by thomasplevy** [comment]
@pondermatic thanks for the bug report and willingness to implement a fix.

I think my preference would be to throw an error message on the admin panel in this specific scenario as opposed to running additional checks in the proposed places. I'm not sure this is the *best* solution but given it seems to be something of an edge case I'd prefer not to fix it by adding additional checks in places that they aren't strictly needed.

I think the best place to put a check in place would be here:

https://github.com/gocodebox/lifterlms/blob/d0098775e5ed9c251913bef51e43484bb677bda1/includes/admin/reporting/tabs/class.llms.admin.reporting.tab.students.php#L48

Since we're actually not using `llms_get_student()` we get an instantiated object (instead of `false`) regardless of whether or not a user with that ID exists.

https://developer.lifterlms.com/reference/functions/llms_get_student/

I think that'll do it

**Comment by thomasplevy** [comment]
@pondermatic I've assigned this to you preemptively under the assumption that you're a good guy and that you are actually going to submit a PR as you've volunteered. Thank you :heart:

**Comment by pondermatic** [comment]
Perhaps we should check the user's existence in `output()` like the [courses tab on the reporting screen](https://github.com/gocodebox/lifterlms/blob/d0098775e5ed9c251913bef51e43484bb677bda1/includes/admin/reporting/tabs/class.llms.admin.reporting.tab.courses.php#L98) does?

```php
	$student = new LLMS_Student( intval( $_GET['student_id'] ) );
	if ( $student->exists() === false ) {
		wp_die( __( 'You do not have permission to access this user.', 'lifterlms' ) );
	}
```

**Comment by thomasplevy** [comment]
Sure, but using `llms_get_student()` is preferable.

EG:

```php
$student = llms_get_student( ... );
if ( ! $student ) { 
   wp_die( ... )
}
```

This function has built-in check to ensure the user exists before instantiating the `LLMS_Student` object. It'll return `false` if the student doesn't exist or `LLMS_Student` if it does.
