### ISSUE TITLE
Access expiration not being respected

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1649]
### Reproduction Steps

+ It's not reproducible from what I've been trying
+ Every membership order with an expiration before May 19th is not expiring as it should. 
+ We have access to a staging site but I couldn't reproduce the issue at all 
+ The few orders set to expire May 19th or later (there's 2) have expired as expected, but everything else before that still has enrollment.
+ In WP Crontrol there is llms_stripe_cancel_expired_subscriptions that has a non action notice, but this is affecting paypal payments too
+ I don't see any stuck processes in tools and utilities
+ he can't remember anything specifically changing around the time of the 19th but he did mention extending access to some users manually. Those may be the ones that expired as expected. On the staging site I was able to get them to expire as expected when i manually changed the date to trigger it. Though then I don't know how to test waiting the original full time.

### Expected Behavior

+ The order should be expiring

### Actual Behavior

+ they're not, and the order note that should show up as a notice for the expiration isn't displaying, but the expire date is set on the orders.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
I found a couple weird things but I don't know if they're relevant:

[27-May-2021 08:52:25 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status='pending' AND a.scheduled_date_gmt <= '2021-05-27 08:52:25' ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Store->has_pending_actions_due, ActionScheduler_DBStore->query_actions

[16-Dec-2020 01:33:59 UTC] PHP Fatal error:  Uncaught Error: Call to a member function end() on bool in /home//public_html/wp-content/plugins/lifterlms/includes/class.llms.ajax.handler.php:714
Stack trace:
#700 /public_html/wp-content/plugins/lifterlms/includes/class.llms.ajax.php(97): LLMS_AJAX_Handler::quiz_end(Array)
#1 /home//public_html/wp-includes/class-wp-hook.php(287): LLMS_AJAX::handle('')
#2 /home//public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /home//public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /home//public_html/wp-admin/admin-ajax.php(184): do_action('wp_ajax_quiz_en...')
#5 {main}
  thrown in /home//public_html/wp-content/plugins/lifterlms/includes/class.llms.ajax.handler.php on line 714


  [05-Jan-2021 17:09:13 UTC] WordPress database error Commands out of sync; you can't run this command now for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status='pending' AND a.scheduled_date_gmt <= '2021-01-05 17:09:13' ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Store->has_pending_actions_due, ActionScheduler_DBStore->query_actions

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.7.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#7) [[removed]/]
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.21.3
Db Version: 4.21.3
Course Catalog: Courses (#626) [[removed]/courses/]
Membership Catalog: Membership Catalog (#601) [[removed]/memberships/]
Student Dashboard: Members Dashboard (#603) [[removed]/members-dashboard/]
Checkout Page: Purchase (#602) [[removed]/purchase/]
Course Catalog Per Page: 12
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: weak
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: GB
Currency: GBP
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image: 307
Cert Bg Width: 900
Cert Bg Height: 700
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 0
PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 1
Manual: Disabled
Manual Logging:
Manual Order: 2


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 71 GB
Php Memory Limit: 1024M
Php Post Max Size: 64M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 180
Php Version: 7.4.16
Software: LiteSpeed
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.4.7
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template:
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

3D FlipBook - Lite Edition: 1.11.1
Astra Pro: 3.4.2
Contact Form 7: 5.4.1
Ditty News Ticker: 2.3.8
Elementor: 3.2.4
LifterLMS: 4.21.3
LifterLMS Helper: 3.2.0
LifterLMS PayPal Gateway: 1.3.0
LifterLMS Stripe Payment Gateway: 5.3.2
Prevent Direct Access: 2.7.4
Prevent Direct Access Gold: 3.3.2
Slide Anything - Responsive Content / HTML Slider and Carousel: 2.3.37
Slimstat Analytics: 4.8.8.1
Slimstat Analytics - IP Address Fix: 1.9.1
Starter Templates: 2.6.10
Tuxedo Big File Uploads: 1.2
WP Content Copy Protection & No Right Click (premium): 9.9
WP Crontrol: 1.10.0
WP Mail SMTP: 2.8.0
Yoast SEO: 16.3


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

HS-167947

**Comment by thomasplevy** [comment]
@nrherron92 can you provide a list of order ids (at least a few) that can be reviewed so i don't have to manulally dig through the data to figure out which ones didn't work right please (seems like you already have the list)

**Comment by nrherron92** [comment]
@thomasplevy 
#6659
#6608
#6601

**Comment by thomasplevy** [comment]
@nrherron92 if you view the "Failed" actions under LLMS -> Status -> Schedule Actions you'll see all of these actions have timed out and failed.

Then look into the error logs and you'll see lots of strange errors. The most glaring is that there are a *tremendous* number of database errors resulting from a lack of available disk space (this is probably database space):

```
WordPress database error Disk full (/tmp/#sql_1f75_55.MAI); waiting for someone to free some space... (errno: 28 "No space left on device") for query ...
```

I haven't attempted to match these error timestamps up with our failed actions but if you look at the debug log and search for "Disk full" you'll see several hundred instances of this error leading me to assume with pretty high certainty that the disk is full causing the queries to be unable to complete and ultimately being marked as "failed" after several retries.

My guess would be that in addition to this the user is having all sorts of other problems too.

It's unclear to me if this is an instance of temporary / swap disk space being full or if it's actually database disk space being exhausted. In either case the user should contact their host and see what they have to say about this.

This isn't really something we can fix. They need more disk space.

**Comment by nrherron92** [comment]
@thomasplevy thank you!
