### ISSUE TITLE
Conflict with Nicepages

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1727]
### Reproduction Steps

+ HS-172888

+ Install LifterLMS *do not activate*
+ Install and activate Nicepages: https://nicepage.com/download-wordpress#
+ Activate LifterLMS

### Expected Behavior

+ LifterLMS turns on as normal and you create courses like a happy elf

### Actual Behavior

+ A fatal error crashes the site like a mean elf.

### Error Messages / Logs

+ Include any relevant error messages or log files

```
Fatal error: Uncaught Error: Call to undefined function wp_get_current_user() in /srv/users/manager/apps/natalie-5-testing/public/wp-content/plugins/lifterlms/includes/class.llms.user.permissions.php:63 Stack trace: #0 /srv/users/manager/apps/natalie-5-testing/public/wp-includes/class-wp-hook.php(303): LLMS_User_Permissions->editable_roles(Array) #1 /srv/users/manager/apps/natalie-5-testing/public/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array) #2 /srv/users/manager/apps/natalie-5-testing/public/wp-admin/includes/user.php(272): apply_filters('editable_roles', Array) #3 /srv/users/manager/apps/natalie-5-testing/public/wp-content/plugins/nicepage/includes/class-np-role-manager.php(19): get_editable_roles() #4 /srv/users/manager/apps/natalie-5-testing/public/wp-content/plugins/nicepage/includes/class-np-role-manager.php(185): NpRoleManager::init() #5 /srv/users/manager/apps/natalie-5-testing/public/wp-content/plugins/nicepage/nicepage.php(48): include_once('/srv/users/mana...') #6 /srv/users/manager/apps/na in /srv/users/manager/apps/natalie-5-testing/public/wp-content/plugins/lifterlms/includes/class.llms.user.permissions.php on line 63

```

### System and Environment Information
+ I had to disable nicepages on the staging site:
<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.8
Debug Mode: No
Debug Log: No
Debug Display: No
Locale: en_GB
Multisite: No
Page For Posts: blogi (#2) [[removed]/blogi/]
Page On Front: etusivu (#50) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.1.3
Db Version: 5.1.3
Course Catalog:(#1158) []
Membership Catalog:(#665) []
Student Dashboard:(#667) []
Checkout Page:(#666) []
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: kurssit
Edit Endpoint: muokkaa-tilia
Lost Password Endpoint: unohtunut-salasana
Vouchers Endpoint: maksuseteli
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: FI
Currency: EUR
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 10.3.29
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 128 MB
Php Memory Limit: 512M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 120
Php Version: 7.4.13
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36


Theme
-------------------------------------------

Name: voimaantumo04
Version: 1.0
Themeuri: https://nicepage.com/wordpress
Authoruri: https://nicepage.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Booster for WooCommerce: 5.4.3
Checkout Finland for WooCommerce: 1.6
Contact Form 7: 5.4.2
Cookie Notice & Compliance for GDPR / CCPA: 2.1.0
Easy Forms for Mailchimp: 6.8.4
Facebook for WooCommerce: 2.6.1
Google Analytics Dashboard for WP (GADWP): 6.8.0
LifterLMS: 5.1.3
LifterLMS WooCommerce: 2.0.11
LifterLMS WPForms: 1.1.0
Mailchimp for WooCommerce: 2.5.2
Shield Security: 11.5.3
WooCommerce: 5.5.2
WooCommerce Shipping & Tax: 1.25.17
Yoast Duplicate Post: 4.1.2
Yoast SEO: 16.8


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: Yes
LifterLMS WPForms: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [X] Locally
+ [X] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
This plugin loads all of it's functionality immediately in favor of waiting for an `init` hook (where most plugins will load their functionality).

Ideally the plugin would also wait for WP to be loaded as to maximize compatibility with other plugins but we can modify our filter to only run if the required function is available.
