### ISSUE TITLE
Buddyboss Menu Setting Certificate Conflict

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2080]
### Reproduction Steps

+ HS-189715
+ Activate BuddyBoss + Buddyboss Platform
+ Go into _Appearance->Menus_
+ Create a menu and set it to display "Profile Dropdown"
<img width="482" alt="image" src="https://user-images.githubusercontent.com/47434271/159948460-6f567326-edf2-4b52-b49d-f15dc04f8b70.png">

### Expected Behavior

+ That this shouldn't affect certificates on the backend

### Actual Behavior

+ With Profile Dropdown selected Certificates (Engagements->certificates) isn't accesible

### Error Messages / Logs

+ Include any relevant error messages or log files
```
Fatal error: Uncaught Error: Call to a member function get_template_version() on bool in /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/admin/post-types/post-tables/class-llms-admin-post-table-certificates.php:97 Stack trace: #0 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): LLMS_Admin_Post_Table_Certificates->add_states(Array, Object(WP_Post)) #1 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array) #2 /srv/users/manager/apps/natalie-test-site/public/wp-admin/includes/template.php(2242): apply_filters('display_post_st...', Array, Object(WP_Post)) #3 /srv/users/manager/apps/natalie-test-site/public/wp-includes/nav-menu.php(840): get_post_states(Object(WP_Post)) #4 [internal function]: wp_setup_nav_menu_item(Object(WP_Post)) #5 /srv/users/manager/apps/natalie-test-site/public/wp-includes/nav-menu.php(764): array_map('wp_setup_nav_me...', Array) #6 /srv/users/manager/apps/natalie-test-site/public/wp-includes/nav-menu-template.php(151): wp_get_nav_menu_items(Object(WP_Term), Array) #7 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/inc/theme/functions.php(1413): wp_nav_menu(Object(stdClass)) #8 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): buddyboss_theme_add_admin_menus(Object(WP_Admin_Bar)) #9 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #10 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(522): WP_Hook->do_action(Array) #11 /srv/users/manager/apps/natalie-test-site/public/wp-includes/admin-bar.php(95): do_action_ref_array('admin_bar_menu', Array) #12 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): wp_admin_bar_render('') #13 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #14 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #15 /srv/users/manager/apps/natalie-test-site/public/wp-admin/admin-header.php(267): do_action('in_admin_header') #16 /srv/users/manager/apps/natalie-test-site/public/wp-admin/edit.php(397): require_once('/srv/users/mana...') #17 {main} thrown in /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/admin/post-types/post-tables/class-llms-admin-post-table-certificates.php on line 97
```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.9.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Homepage (#1398) [https://natalie-test-site.myliftersite.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: yes
Stripe Order: 1
Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36


Theme
-------------------------------------------

Name: BuddyBoss Theme
Version: 1.8.3
Themeuri: https://www.buddyboss.com/
Authoruri: https://www.buddyboss.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

BuddyBoss Platform: 1.8.5
LifterLMS: 6.0.0


Integrations
-------------------------------------------

BbPress: Yes
BuddyPress: Yes


Template Overrides
-------------------------------------------

content-certificate.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.5.0)
achievements/loop.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
achievements/template.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.6)
certificates/loop.php (ver: 3.14.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
certificates/preview.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
course/author.php (ver: 4.11.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.25.0)
course/lesson-preview.php (ver: 5.7.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.4.0)
loop/author.php (ver: 3.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.0.0)
loop/content.php (ver: 3.14.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
loop/featured-image.php (ver: 3.35.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
myaccount/dashboard-section.php (ver: 3.30.1): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.1)
myaccount/header.php (ver: 3.14.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
myaccount/my-grades-single-table.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.24.0)
myaccount/my-notifications.php (ver: 3.30.3): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.3)
myaccount/my-orders.php (ver: 3.17.6): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.6)
myaccount/view-order.php (ver: 6.0.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
product/access-plan-pricing.php (ver: 3.29.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.29.0)
quiz/results-attempt-questions-list.php (ver: 5.3.0): /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.8)



```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
@nrherron92 
Thanks, I was able to reproduce it.
(note: at least an item must be added to the menu in order to reproduce this issue.)

The thing is that [this filter](https://developer.wordpress.org/reference/hooks/display_post_states/), despite its description, is called whenever `get_post_states($post)` is called, not necessarily when displaying a post list table, so we need to be sure the `$post` we're processing is actually a certificate. 

The BuddyBoss theme is doing anything weird, it only adds that menu to the dropdown menu in the admin bar via `$wp_admin_bar->add_menu()`, that method will (indirectly) call `get_post_states($post)` on the menu item (post).
