### ISSUE TITLE
Save Certificate Resulting in Fatal Error

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2241]
### Reproduction Steps

+ HS-200002
+ This is a bit of a tough one, a free user is having an issue when trying to save certificates that it is resulting in a fatal error (below) 
+ I can't recreate this and since it's a free user we can't get credentials, so I was wondering what we could do with next steps to get to the bottom of it, or if there's anything in the error that can point towards what could be causing the issue.
+ The site is also behind a corporate firewall which may be contributing to the issue as well?

### Expected Behavior

+ certificate saves

### Actual Behavior

+ fatal error

### Error Messages / Logs

+ Include any relevant error messages or log files
```

2022/08/22 10:26:38 [error] 753#753: *74 FastCGI sent in stderr: "PHP message: HP Fatal error: Uncaught Error: Call to a member function appendChild() on nul in /var/www/html/wp-content/plugins/lifterlms/includes/class.llms.certificatesphp:361

Stack trace:

#0 /var/www/html/wp-content/plugins/lifterlms/includes/class.llms.certificates.hp(257): LLMS_Certificates->modify_dom()

#1 /var/www/html/wp-content/plugins/lifterlms/includes/class.llms.certificates.hp(169): LLMS_Certificates->get_export_html()

#2 /var/www/html/wp-content/plugins/lifterlms/includes/class.llms.certificates.hp(226): LLMS_Certificates->generate_export()

#3 /var/www/html/wp-content/plugins/lifterlms/includes/controllers/class.llms.cntroller.certificates.php(218): LLMS_Certificates->get_export()

#4 /var/www/html/wp-content/plugins/lifterlms/includes/controllers/class.llms.cntroller.certificates.php(175): LLMS_Controller_Certificates->download()

#5 /var/www/html/wp-includes/class-wp-hook.php(307): LLMS_Controller_Certificats->maybe_handle_reporting_actions()

#6 /var/www/html/wp-includes/cl" while reading response header from upstream, cient: 10.234.45.125, server: csa.basf.net, request: "POST /certificate/4gv/ HTT/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "csa.basf.net", referrer: "htps://csa.basf.net/certificate/4gv/"


```

### System and Environment Information

<details>
<summary>System Report</summary>

```

System Report

Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 6.0.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Blog (#30) [[removed]/blog/]
Page On Front: Home (#29) [[removed]/courses]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: No


Settings
-------------------------------------------

Version: 6.9.0
Db Version: 6.9.0
Course Catalog: Course Catalog (#24) [[removed]/courses/]
Membership Catalog: Learning Paths (#25) [[removed]/memberships/]
Student Dashboard: Dashboard (#27) [[removed]/dashboard/]
Checkout Page: Purchase (#26) [[removed]/purchase/]
Course Catalog Per Page: 20
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint:
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength:
Terms Required: no
Terms Page: Not Set
Checkout Names:
Checkout Address:
Checkout Phone:
Checkout Email Confirmation: no
Open Registration: no
Registration Names:
Registration Address:
Registration Phone:
Registration Voucher:
Registration Email Confirmation: no
Account Names:
Account Address:
Account Phone:
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image:
Cert Bg Width:
Cert Bg Height:
Cert Legacy Compat:


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging:
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 64 MB
Php Memory Limit: 256M
Php Post Max Size: 64M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.1.2
Software: nginx/1.18.0
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54


Theme
-------------------------------------------

Name: BuddyBoss Child
Version: 1.0.1
Themeuri: https://www.buddyboss.com/
Authoruri: https://www.buddyboss.com/
Template: buddyboss-theme
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

BuddyBoss Platform: 2.0.8
BuddyBoss Platform Pro: 2.1.1
Classic Widgets: 0.3
Easy WP SMTP: 1.4.7
Elementor: 3.7.1
Elementor Pro: 3.7.3
Imagify: 2.0
LifterLMS: 6.9.0
Loco Translate: 2.6.2
myCred: 2.4.8.1
myCred - LifterLMS Integration: 1.2
Nginx Cache: 1.0.5
Page Links To: 3.3.6
Redis Object Cache: 2.0.26
Site Reviews: 5.25.1
Site Reviews: Review Forms: 1.9.4
Site Reviews: Review Themes: 1.0.0-beta18
WPForms: 1.7.6
WPO365 | LOGIN: 18.2


Integrations
-------------------------------------------

BbPress: No
BuddyPress: Yes


Template Overrides
-------------------------------------------

content-certificate.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.5.0)
achievements/loop.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
achievements/template.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.6)
certificates/actions.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 6.0.0)
certificates/content-legacy.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 6.0.0)
certificates/content.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 6.0.0)
certificates/loop.php (ver: 3.14.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
certificates/preview.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
course/author.php (ver: 4.11.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.25.0)
course/lesson-preview.php (ver: 5.7.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 4.4.0)
loop/author.php (ver: 3.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.0.0)
loop/content.php (ver: 3.14.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
loop/featured-image.php (ver: 3.35.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
myaccount/dashboard-section.php (ver: 3.30.1): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.1)
myaccount/header.php (ver: 3.14.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
myaccount/my-grades-single-table.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.24.0)
myaccount/my-notifications.php (ver: 3.30.3): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.3)
myaccount/my-orders.php (ver: 3.17.6): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.6)
myaccount/view-order.php (ver: 6.0.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
product/access-plan-pricing.php (ver: 3.29.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.29.0)
quiz/results-attempt-questions-list.php (ver: 5.3.0): /var/www/html/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.8)

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
Hard to say what's going wrong.
The error is pretty clear, for some reason on this user's website, the certificate HTML page retrieved when clicking on Save, doesn't have any `<head>` tag, hence the error here:
https://github.com/gocodebox/lifterlms/blob/6.9.0/includes/class.llms.certificates.php#L360

Why does that happen?
That's just a sign of something going wrong to me, like that the server replied with an error page or something. Might it depend on the firewall you were mentioning. It might... Can they disable it and see if it still occurs?
Also, can they rule-out any plugins conflict?

**Comment by thomasplevy** [comment]
@nrherron92 any new info here?

**Comment by nrherron92** [comment]
Nope user never replied. I'll open again if they do
