### ISSUE TITLE
Error in Quiz Reporting

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2270]
### Reproduction Steps

+ HS-201478
+ Staging site linked on ticket
+ Can't reproduce locally
+ Head into site and take the feedback quiz (if there have been no attempts on the day you check)
+ Then head into Reporting->Quiz->Feedback Survey
+ On the overview for the Average Grade/Attempts column there is a critical error.  

### Expected Behavior

+ the two tiles should show 0

### Actual Behavior

+ critical error

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->
Error Details
=============
An error of type E_ERROR was caused in line 458 of the file /nas/content/live/nationalgas/wp-content/plugins/lifterlms/includes/admin/reporting/class.llms.admin.reporting.php. Error message: Uncaught DivisionByZeroError: Division by zero in /nas/content/live/nationalgas/wp-content/plugins/lifterlms/includes/admin/reporting/class.llms.admin.reporting.php:458
Stack trace:
#0 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/templates/admin/reporting/tabs/quizzes/overview.php(65): LLMS_Admin_Reporting::output_widget(Array)
#1 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('/nas/content/li...')
#2 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/templates/admin/reporting/tabs/quizzes/quiz.php(48): llms_get_template('admin/reporting...', Array)
#3 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('/nas/content/li...')
#4 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/includes/admin/reporting/tabs/class.llms.admin.reporting.tab.quizzes.php(98): llms_get_template('admin/reporting...', Array)
#5 /nas/content/live/nationalgas/wp-includes/class-wp-hook.php(307): LLMS_Admin_Reporting_Tab_Quizzes->output('')
#6 /nas/content/live/nationalgas/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#7 /nas/content/live/nationalgas/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#8 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/templates/admin/reporting/reporting.php(49): do_action('llms_reporting_...')
#9 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('/nas/content/li...')
#10 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/includes/admin/reporting/class.llms.admin.reporting.php(381): llms_get_template('admin/reporting...', Array)
#11 /nas/content/live/nationalgas/wp-content/plugins/lifterlms/includes/admin/class.llms.admin.menus.php(332): LLMS_Admin_Reporting->output()
#12 /nas/content/live/nationalgas/wp-includes/class-wp-hook.php(307): LLMS_Admin_Menus->reporting_page_init('')
#13 /nas/content/live/nationalgas/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#14 /nas/content/live/nationalgas/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#15 /nas/content/live/nationalgas/wp-admin/admin.php(259): do_action('lifterlms_page_...')
#16 {main}
thrown

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 6.0.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#1909) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.10.2
Db Version: 6.10.2
Course Catalog: Course Catalog (#17) [[removed]/courses/]
Membership Catalog:(#18) []
Student Dashboard: Orientation Dashboard (#20) [[removed]/dashboard/]
Checkout Page: Purchase (#19) [[removed]/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: 
Edit Endpoint: 
Lost Password Endpoint: lost-password
Vouchers Endpoint: 
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 
Cert Bg Height: 
Cert Legacy Compat: 


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.39
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 50 MB
Php Memory Limit: 512M
Php Post Max Size: 100M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 43300
Php Version: 8.0.20
Software: nginx
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: Astra Child
Version: 1.0.0
Themeuri: 
Authoruri: http://wpastra.com/about/
Template: astra
Child Theme: Yes
Llms Support: Yes


Plugins
-------------------------------------------

LifterLMS: 6.10.2


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment]
This is happening because there's no possible points total on the quiz. So the logic to give an average grade is failing because of a division by zero...

It's a pretty easy fix. There's no test cases covering this and it probably isn't something anyone's ever noticed because I think that using quizzes in this way is probably not very common.

We'll get it cleaned up in the next release.

Also: there's no workaround. THe code is broken.

**Comment by nrherron92** [comment]
Thank you 💟

**Comment by thomasplevy** [comment]
@nrherron92 this is fixed, will release tomorrow in the AM
