### ISSUE TITLE
Assignment Submission not Queuing to Send

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2302]
### Reproduction Steps

+ HS-208142
+ Make sure to enable assignment submission notification
+ On user's site, go into an assignment and submit for grading

### Expected Behavior

+ An email is sent for the submission notice

### Actual Behavior

+ In the LifterLMS logs it looks like it is sending, but it does not show up in mail logging for the smtp even with an error
+ Works fine on staging 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
[23-Nov-2022 18:34:28 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_date() on null in /home/slamacad/public_html/wp-content/plugins/lifterlms/includes/notifications/views/class.llms.notification.view.payment.retry.php:175
Stack trace:
#0 /home/slamacad/public_html/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.notification.view.php(628): LLMS_Notification_View_Payment_Retry->set_merge_data('{{NEXT_PAYMENT_...')
#1 /home/slamacad/public_html/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.notification.view.php(693): LLMS_Abstract_Notification_View->get_merged_string('Automatic payme...')
#2 /home/slamacad/public_html/wp-content/plugins/lifterlms/includes/notifications/processors/class.llms.notification.processor.email.php(62): LLMS_Abstract_Notification_View->get_subject()
#3 /home/slamacad/public_html/wp-content/plugins/lifterlms/vendor/deliciousbrains/wp-background-processing/classes/wp-background-process.php(301): LLMS_Notification_Processor_Email->task(46074)
#4 /home/slamacad/public_html/wp-content in /home/slamacad/public_html/wp-content/plugins/lifterlms/includes/notifications/views/class.llms.notification.view.payment.retry.php on line 175

```

### System and Environment Information

<details>
<summary>System Report</summary>

```

Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.8.6
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: home (#10) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.0.0
Db Version: 6.4.0
Course Catalog: course catalog – old (#39214) [[removed]/course-catalog-old/]
Membership Catalog:(#4538) []
Student Dashboard: Dashboard-accountstatus (#53902) [[removed]/dashboard-accountstatus/]
Checkout Page: Enrollment (#55448) [[removed]/enrollment/]
Course Catalog Per Page: -1
Course Catalog Sorting: title,ASC
Membership Catalog Per Page: -1
Membership Catalog Sorting: title,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Terms and Conditions (#51508) [[removed]/terms/]
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: course-confirmation
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image: 164
Cert Bg Width:
Cert Bg Height:
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: yes
Stripe Order: 0
Authorize.Net: Disabled
Authorize.Net Test Mode: Disabled
Authorize.Net Logging: no
Authorize.Net Order: 1
PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 10
Manual: Disabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 128 MB
Php Memory Limit: 1024M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 7.4.32
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: InspiroChild
Version: 1.0
Themeuri:
Authoruri:
Template: inspiro
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

ActiveCampaign: 8.1.10
Beaver Builder Addons by WPZOOM: 1.3.4
Beaver Builder Plugin (Standard Version): 2.5.3.1
Beaver Builder Sticky Column: 1.5.3
Bookly: 20.7
Bookly Pro (Add-on): 4.7
Cazarin Shortcode: 1.0
Content Slider Block: 3.0.4
Duplicate Menu: 0.2.2
Easy Pixels by JEVNET: 2.13
Easy Registration Conditional Fields & Actions: 1.2.1
Easy Registration Forms: 2.1.1
Easy Registration PayPal Integration: 1.0.5
Events Manager: 6.1.2.1
Frontend Reset Password: 1.2
GDPR Cookie Consent: 2.1.1
Hotjar: 1.0.14
LifterLMS: 7.0.0
LifterLMS Assignments: 2.0.1
LifterLMS Authorize.Net Payment Gateway: 1.1.0
LifterLMS Customizations: 1.0.0
LifterLMS PayPal Gateway: 1.4.0
LifterLMS Stripe Payment Gateway: 5.4.0
LifterLMS WPForms: 1.1.2
LoginPress - Customizing the WordPress Login Screen.: 1.6.2
LoginWP (Formerly Peter's Login Redirect): 3.0.3.0
ManageWP - Worker: 4.9.14
MaxButtons: 9.0
Max Mega Menu: 2.9.6
Max Mega Menu - Pro Addon: 2.2.4
myCred: 2.4.4.2
Pixel Cat Personal: 2.6.6
Post SMTP: 2.1.10
Redirection: 5.3.4
SendWP: 1.3.1
Site Kit by Google: 1.73.0
Social Icons Widget & Block by WPZOOM: 4.2.4
TLS 1.2 Compatibility Test: 1.0.1
WP Change Email Sender: 1.0
WPCode - Insert Headers, Footers, and Code Snippets: 2.0.3
WP Crontrol: 1.12.1
WPForms: 1.7.6
WPForms Form Abandonment: 1.7.0
WPForms PayPal Commerce: 1.0.0
WPForms PayPal Standard: 1.5.0
WPForms Stripe: 2.6.1
WPForms User Registration: 2.1.0
WPFront Notification Bar: 3.2.0
WP Simple Pay Pro: 4.4.5
WPvivid Backup Plugin: 0.9.74


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS WPForms: Yes


Template Overrides
------------------------------------------- 

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
@nrherron92 
the logged error:
`[23-Nov-2022 18:34:28 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_date() on null in /home/slamacad/public_html/wp-content/plugins/lifterlms/includes/notifications/views/class.llms.notification.view.payment.retry.php:175
`
Is about a different notification (payment retry) which is stuck due to a fatal error and it's clogging the queue.
As result of this, if you look into the Status->Tools - Delete processor batches, you'll see that "There are currently 2714 pending batches that will be deleted.". So that tool can be used to clean the queue but of course all the pending processors will be cleaned as well. This means that notifications that were not sent will not be sent, but new notifications will be.
In [this PR](https://github.com/gocodebox/lifterlms/pull/2253) I implemented a solution to fix avoid this kind of clogging.
