### ISSUE TITLE
Free Access Plan + My Calendar Plugin

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2332]
### Reproduction Steps

+ HS-211482
+ Enable LifterLMS + My Calendar Plugin: https://wordpress.org/plugins/my-calendar/
+ Create a membership with a no payment required access plan
+ on the front end attempt to purchase the access plan

### Expected Behavior

+ The checkout page comes up as normal

### Actual Behavior

+ there's a critical error

### Error Messages / Logs

+ Include any relevant error messages or log files
```
2023/01/04 21:59:43 [error] 29729#29729: *390718 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function mc_search_results_title(), 1 passed in /www/inventrightmembers_122/public/wp-includes/class-wp-hook.php on line 308 and exactly 2 expected in /www/inventrightmembers_122/public/wp-content/plugins/my-calendar/my-calendar-search.php:166
Stack trace:
#0 /www/inventrightmembers_122/public/wp-includes/class-wp-hook.php(308): mc_search_results_title('Student Informa...')
#1 /www/inventrightmembers_122/public/wp-includes/plugin.php(205): WP_Hook->apply_filters('Student Informa...', Array)
#2 /www/inventrightmembers_122/public/wp-content/plugins/lifterlms/includes/functions/llms-functions-forms.php(93): apply_filters('the_title', 'Student Informa...')
#3 /www/inventrightmembers_122/public/wp-content/plugins/lifterlms/includes/shortcodes/class.llms.shortcode.checkout.php(313): llms_get_form_title('checkout', Array)
#4 /www/inventrightmembers_122/public/wp-content/plugins/lifterlms/includes/shortcodes/class.llms.shortc" while reading response header from upstream, client: 24.176.166.211, server: inventtraining.com, request: "GET /purchase/?plan=12420 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8.0-fpm-inventrightmembers.sock:", host: "inventtraining.com:48488"

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 6.1.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#33) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.0.1
Db Version: 7.0.1
Course Catalog: Course Catalog (#23) [[removed]/courses/]
Membership Catalog: Membership Catalog (#24) [[removed]/?page_id=24]
Student Dashboard: Dashboard (#26) [[removed]/dashboard/]
Checkout Page: Purchase (#25) [[removed]/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength:
Terms Required: yes
Terms Page: Student Agreement (#231) [[removed]/student-agreement/]
Checkout Names:
Checkout Address:
Checkout Phone:
Checkout Email Confirmation: no
Open Registration: no
Registration Names:
Registration Address:
Registration Phone:
Registration Voucher:
Registration Email Confirmation: no
Account Names:
Account Address:
Account Phone:
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: If you have any questions please contact support at 1-800-701-7993 or chat via the website.
Email Header Image: 39
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 0
PayPal: Disabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 1
Manual: Disabled
Manual Logging: no
Manual Order: 2


Server
-------------------------------------------

Mysql Version: 10.5.13
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 128 MB
Php Memory Limit: 256M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 8.0.21
Software: nginx/1.21.4
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0


Theme
-------------------------------------------

Name: Divi
Version: 4.19.4
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template:
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Advanced Editor Tools (previously TinyMCE Advanced): 5.6.0
AudioIgniter: 1.9.0
AyeCode Connect: 1.2.12
bbPress: 2.6.9
Business Directory Plugin: 6.3.1
Business Directory Plugin - Enhanced Categories Module: 5.0.12
Business Directory Plugin - Migrator: 5.0.4
Business Directory Premium: 5.5
Business Directory Restrictions: 5.1
Disable User Login: 1.3.3
Duplicate Pages, Posts & CPT: 1.2
Easy Custom Sidebars: 2.0.1
File Upload Types: 1.2.2
Gravity Forms: 2.6.8
Gravity PDF: 6.5.3
Image Map HotSpot with Lightbox: 1.3.6
Ivory Search: 5.4.10
LifterLMS: 7.0.1
LifterLMS Advanced Quizzes: 3.0.0
LifterLMS Advanced Videos: 1.0.0-beta.19
LifterLMS Assignments: 2.0.1
LifterLMS Custom Fields: 2.0.2
LifterLMS Customizations: 1.0.0
LifterLMS Gravity Forms: 2.1.3
LifterLMS Groups: 1.0.0-beta.21
LifterLMS Helper: 3.4.2
LifterLMS Labs: 1.6.0
LifterLMS PayPal Gateway: 1.4.0
LifterLMS PDFs: 2.1.0
LifterLMS Private Areas: 1.1.5
LifterLMS Progress Reset: 1.0.2
LifterLMS Social Learning: 1.5.0
LifterLMS Stripe Payment Gateway: 5.5.0
Loco Translate: 2.6.3
LoginWP - Pro: 4.0.6.0
My Calendar: 3.3.25
My Calendar Pro: 2.2.0
Posts 2 Posts: 1.7
Post Type Switcher: 3.2.1
PublishPress Capabilities: 2.6.1
Restrict User Access: 2.4.1
Safe SVG: 2.0.3
SendWP: 1.3.1
Title Remover: 1.2.1
Ultimate Blocks: 2.5.4
User Menus: 1.3.1
User Profile Picture: 2.6.0
Vimeography: 2.3.1
Vimeography Developer Bundle: 2.1.1
Vimeography Pro: 2.1.1
WP-UserOnline: 2.88.1


Integrations
-------------------------------------------

BbPress: Yes
BuddyPress: No
LifterLMS Groups: Yes
LifterLMS Gravity Forms: Yes
LifterLMS PDFs: Yes
LifterLMS Private Areas: No
LifterLMS Social Learning: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
------------------------------------------- 

```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment]
So the issue is here:
https://github.com/gocodebox/lifterlms/blob/7.0.1/includes/functions/llms-functions-forms.php#L93
we need to use the same _signature_ of the WP hook here:
https://developer.wordpress.org/reference/hooks/the_title/
so
`apply_filters( 'the_title', get_post_meta( $post->ID, '_llms_form_title_free_access_plans', true ) )`
must become
`apply_filters( 'the_title', get_post_meta( $post->ID, '_llms_form_title_free_access_plans', true ), $post->ID )`
