### ISSUE TITLE
"Certificate Title" block will not render

### ISSUE THREAD

**Issue by brianhogg** [gocodebox/lifterlms#2696]
### Reproduction Steps

1. Go to Engagements > Certificates, then click "Add New"

### Expected Behavior

All blocks render without error

### Actual Behavior

The "Certificate Title" block shows an error that it cannot be previewed

### Error Messages / Logs

In console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'pattern/overrides')
    at block-editor.js?ver=2ee220318f8a232809ac:37051:43
    at renderWithHooks (react-dom.development.js:15486:18)
    at mountIndeterminateComponent (react-dom.development.js:20098:13)
    at beginWork (react-dom.development.js:21621:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27485:7)
    at performUnitOfWork (react-dom.development.js:26591:12)
    at workLoopSync (react-dom.development.js:26500:5)
```

```
react-dom.development.js:18704 The above error occurred in the <WithBlockBindingSupport(HeadingEdit)> component:

    at https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:37044:68
    at edit (https://lifter2.test/wp-content/plugins/lifterlms/blocks/certificate-title/index.js?ver=d8a1f4fdd2e418ff82df:13:1717)
    at Edit (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:39062:5)
    at https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:17552:21
    at https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:6359:69
    at https://lifter2.test/wp-content/plugins/lifterlms-blocks/assets/js/llms-blocks.js?ver=76110ae09aa41cf7417e:5:170
    at FilteredComponentRenderer (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:70586:9)
    at EditWithGeneratedProps (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:39080:5)
    at BlockEdit (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:39266:3)
    at BlockCrashBoundary (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:39570:5)
    at BlockListBlock (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:40567:10)
    at https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:35359:5
    at https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:17621:99
    at FilteredComponentRenderer (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:70586:9)
    at https://lifter2.test/wp-includes/js/dist/data.js?ver=6f178ef23ef546c51cae:4489:25
    at BlockListBlockProvider (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:40917:5)
    at Items (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:50795:3)
    at BlockListItems
    at div
    at block_list_Root (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:50689:3)
    at BlockList
    at RecursionProvider (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:67517:3)
    at div
    at WritingFlow (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:43580:3)
    at div
    at BlockTools (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:55716:3)
    at ExperimentalBlockCanvas (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:56245:3)
    at div
    at Resizable (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:65354:28)
    at UnforwardedResizableBox (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:66399:3)
    at ResizableEditor (https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:24413:3)
    at div
    at VisualEditor (https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:24628:3)
    at SlotComponent (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:33330:5)
    at Slot
    at UnforwardedSlot (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:33890:5)
    at EditCanvasContainerSlotSlot
    at div
    at NavigableRegion (https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:7497:3)
    at div
    at div
    at div
    at InterfaceSkeleton (https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:7584:3)
    at EditorInterface (https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:24959:3)
    at Layout (https://lifter2.test/wp-includes/js/dist/edit-post.js?ver=31dde9e0afebadcf425c:2763:3)
    at ErrorBoundary (https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:9270:5)
    at BlockRefsProvider (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:19796:3)
    at Provider (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:33905:3)
    at https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:41798:5
    at https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:41336:3
    at BlockContextProvider (https://lifter2.test/wp-includes/js/dist/block-editor.js?ver=2ee220318f8a232809ac:39017:3)
    at EntityProvider (https://lifter2.test/wp-includes/js/dist/core-data.js?ver=1b304f4025915ff3c84b:6964:3)
    at EntityProvider (https://lifter2.test/wp-includes/js/dist/core-data.js?ver=1b304f4025915ff3c84b:6964:3)
    at https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:21362:3
    at https://lifter2.test/wp-includes/js/dist/editor.js?ver=e15506639990b108fc28:18997:3
    at SlotFillProvider (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:33743:3)
    at provider_SlotFillProvider (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:33841:3)
    at Provider (https://lifter2.test/wp-includes/js/dist/components.js?ver=54eab95952fe254d64e9:33905:3)
    at Editor (https://lifter2.test/wp-includes/js/dist/edit-post.js?ver=31dde9e0afebadcf425c:3062:11)

React will try to recreate this component tree from scratch using the error boundary you provided, BlockCrashBoundary.
```

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by brianhogg** [comment]
Looks like we might be using some internals to render the `HeadingEdit` component and things have changed a bit in WP 6.6. Needs a "context" part when using that component.
