### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by doccannabico** [gocodebox/lifterlms#2787]
I was modifying a lesson while suddenly got a fatal error. I have managed to deactivate lms and my site works but I can not activate Lifter again because it says it triggers a fatal error. Tried uninstalling andd installing from zip but it doesnt work. and also deactivated all the other plugins but even that way lifterlms wont activate. Also purged all the caches in between to no avail.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

[31-Oct-2024 01:28:10 UTC] PHP Warning:  require_once(/home/u416307122/domains/doccannabico.com/public_html/wp-content/plugins/lifterlms/includes/class.llms.l10n.js.php): Failed to open stream: No such file or directory in /home/u416307122/domains/doccannabico.com/public_html/wp-content/plugins/lifterlms/includes/class-llms-loader.php on line 272
[31-Oct-2024 01:28:10 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/u416307122/domains/doccannabico.com/public_html/wp-content/plugins/lifterlms/includes/class.llms.l10n.js.php' (include_path='.:/opt/alt/php82/usr/share/pear:/opt/alt/php82/usr/share/php:/usr/share/pear:/usr/share/php') in /home/u416307122/domains/doccannabico.com/public_html/wp-content/plugins/lifterlms/includes/class-llms-loader.php:272
Stack trace:
#0 /home/u416307122/domains/doccannabico.com/public_html/wp-content/plugins/lifterlms/includes/class-llms-loader.php(131): LLMS_Loader->includes()
#1 /home/u416307122/domains/doccannabico.com/public_html/wp-content/plugins/lifterlms/includes/class-llms-loader.php(456): LLMS_Loader->__construct()
#2 /home/u416307122/domains/doccannabico.com/public_html/wp-content/plugins/lifterlms/lifterlms.php(49): require_once('/home/u41630712...')
#3 /home/u416307122/domains/doccannabico.com/public_html/wp-admin/includes/plugin.php(2387): include_once('/home/u41630712...')
#4 /home/u416307122/domains/doccannabico.com/public_html/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape()
#5 /home/u416307122/domains/doccannabico.com/public_html/wp-admin/plugins.php(60): activate_plugin()
#6 {main}
  thrown in /home/u416307122/domains/doccannabico.com/public_html/wp-content/plugins/lifterlms/includes/class-llms-loader.php on line 272
[31-Oct-2024 01:28:11 UTC] Error de evento de reprogramación de cron para el gancho: llms_end_idle_sessions. Código de error: invalid_schedule. Mensaje de error: El evento programado no existe.. Datos: {"schedule":"every_five_mins","args":[],"interval":300}

### System and Environment Information

<details>
<summary>System Report</summary>

<!-- Paste your System Report between the three backticks below this line -->
```

```

</details>


This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by SaeedMasri** [comment]
Reverting to version 7.8.0 brought the website back, until they fix it!

Get the previous version from here:
https://wordpress.org/plugins/lifterlms/advanced

**Comment by brianhogg** [comment]
@doccannabico Thanks for the report! Version 7.8.2 should resolve this if the `class.llms.l10n.js.php` file is somehow deleted from our plugin. We believe a security or malware plugin was incorrectly identifying a file from our plugin as malicious and deleting it. To prevent the fatal error, we've made it produce a warning instead of a fatal error, and renamed the file in an attempt to avoid the file being flagged incorrectly.
