### ISSUE TITLE
Connect Mailhawk fails, SendWP fails then works on refresh

### ISSUE THREAD

**Issue by brianhogg** [gocodebox/lifterlms#2792]
### Reproduction Steps

1. Go to LifterLMS Settings > Engagements
2. Click "Connect MailHawk"

### Expected Behavior

MailHawk config starts

### Actual Behavior

500 error on the ajax call, though the plugin is installed.

### Error Messages / Logs

+ Include any relevant error messages or log files
If mailhawk isn't already installed:

```
PHP Fatal error:  Uncaught Error: Call to undefined function sprtinf() in /Users/brianhogg/laravel/lifter2/wp-content/plugins/lifterlms/includes/abstracts/llms-abstract-email-provider.php:327
Stack trace:
#0 /Users/brianhogg/laravel/lifter2/wp-content/plugins/lifterlms/includes/abstracts/llms-abstract-email-provider.php(293): LLMS_Abstract_Email_Provider->install()
#1 /Users/brianhogg/laravel/lifter2/wp-content/plugins/lifterlms/includes/abstracts/llms-abstract-email-provider.php(230): LLMS_Abstract_Email_Provider->do_remote_install()
#2 /Users/brianhogg/laravel/lifter2/wp-includes/class-wp-hook.php(324): LLMS_Abstract_Email_Provider->ajax_callback_remote_install('')
#3 /Users/brianhogg/laravel/lifter2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /Users/brianhogg/laravel/lifter2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /Users/brianhogg/laravel/lifter2/wp-admin/admin-ajax.php(192): do_action('wp_ajax_llms_ma...')
#6 /Users/brianhogg/.composer/vendor/laravel/valet/server.php(110): require('/Users/brianhog...')
#7 {main}
  thrown in /Users/brianhogg/laravel/lifter2/wp-content/plugins/lifterlms/includes/abstracts/llms-abstract-email-provider.php on line 327
```

if it is:

```
PHP Fatal error:  Uncaught Error: Call to undefined function MailHawk\get_admin_mailhawk_uri() in /Users/brianhogg/laravel/lifter2/wp-content/plugins/lifterlms/includes/admin/class-llms-mailhawk.php:46
Stack trace:
#0 /Users/brianhogg/laravel/lifter2/wp-content/plugins/lifterlms/includes/abstracts/llms-abstract-email-provider.php(303): LLMS_MailHawk->do_remote_install_success()
#1 /Users/brianhogg/laravel/lifter2/wp-content/plugins/lifterlms/includes/abstracts/llms-abstract-email-provider.php(230): LLMS_Abstract_Email_Provider->do_remote_install()
#2 /Users/brianhogg/laravel/lifter2/wp-includes/class-wp-hook.php(324): LLMS_Abstract_Email_Provider->ajax_callback_remote_install('')
#3 /Users/brianhogg/laravel/lifter2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /Users/brianhogg/laravel/lifter2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /Users/brianhogg/laravel/lifter2/wp-admin/admin-ajax.php(192): do_action('wp_ajax_llms_ma...')
#6 /Users/brianhogg/.composer/vendor/laravel/valet/server.php(110): require('/Users/brianhog...')
#7 {main}
  thrown in /Users/brianhogg/laravel/lifter2/wp-content/plugins/lifterlms/includes/admin/class-llms-mailhawk.php on line 46
```

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by brianhogg** [comment]
Both MailHawk and SendWP have the issue where it fails initially because though the plugin is activated, the code within it (ie. defined constants, functions) aren't yet visible in the request.

**Comment by brianhogg** [comment]
Removed Mailhawk since the signup link doesn't seem to be working.
