### ISSUE TITLE
fatal error resulting from deleted quiz questions

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#640]
When reviewing a quiz as either student or admin the following error will be thrown as a result of the quiz question no longer existing in the database:

````
Fatal error: Uncaught Error: Call to a member function get_auto_grade_type() on null in ***/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.question.php:244
Stack trace:
#0 ***/lifterlms/includes/models/model.llms.quiz.attempt.php(542): LLMS_Quiz_Attempt_Question->get_status()
#1 ***/lifterlms/includes/models/model.llms.quiz.attempt.php(116): LLMS_Quiz_Attempt->is_auto_gradeable()
#2 ***/lifterlms/includes/controllers/class.llms.controller.admin.quiz.attempts.php(91): LLMS_Quiz_Attempt->calculate_grade()
#3 ***/lifterlms/includes/controllers/class.llms.controller.admin.quiz.attempts.php(51): LLMS_Controller_Admin_Quiz_Attempts->save_grade(Object(LLMS_Quiz_Attempt))
#4 ***/wp-includes/class-wp-hook.php(286): LLMS_Controller_Admin_Quiz_Attempts-> in ***/lifterlms/includes/models/model.llms.quiz.attempt.question.php on line 244
```

**Comment by actual-saurabh** [comment]
https://github.com/gocodebox/lifterlms/issues/840
