### ISSUE TITLE
User capabilities filter throws fatal error on comments

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#789]
```
<div class="comment-author vcard">
<img alt='' src='https://secure.gravatar.com/{url}' srcset='https://secure.gravatar.com/avatar/{url}' class='avatar avatar-32 photo' height='32' width='32' />
<b class="fn"><a href='http://testsite.com' rel='external nofollow' class='url'>Admin Author Name</a></b>
<span class="says">says:</span>
</div>
<div class="comment-metadata">
<a href="https://lesson_url/#comments/4378">
<time datetime="2018-10-09T11:11:09-07:00"> October 9, 2018 at 11:11 AM </time>
</a>

<br /> <b>Fatal error</b>:  Uncaught Error: Call to undefined method LLMS_Achievement::get() in /path/to/wp/wp-content/plugins/lifterlms/includes/llms.functions.core.php:815
--
  | Stack trace:
  | #0 /path/to/wp/wp-content/plugins/lifterlms/includes/models/model.llms.instructor.php(226): llms_get_post_parent_course(Object(LLMS_Achievement))
  | #1 /path/to/wp/wp-content/plugins/lifterlms/includes/class.llms.user.permissions.php(110): LLMS_Instructor-&gt;is_instructor('4378')
  | #2 /path/to/wp/wp-content/plugins/lifterlms/includes/class.llms.user.permissions.php(78): LLMS_User_Permissions-&gt;edit_others_lms_content(Array, Array, Array)
  | #3 /path/to/wp/wp-includes/class-wp-hook.php(288): LLMS_User_Permissions-&gt;handle_caps(Array, Array, Array)
  | #4 /path/to/wp/wp-includes/plugin.php(208): WP_Hook-&gt;apply_filters(Array, Array)
  | #5 /path/to/wp/ in <b>/path/to/wp/wp-content/plugins/lifterlms/includes/llms.functions.core.php</b> on line <b>815</b>
<br />
```
https://github.com/gocodebox/lifterlms/blob/cdbee2b4b3bfabf3339bd6870f3d3af8e9227da0/includes/class.llms.user.permissions.php#L19 filters `user_has_cap` which runs

https://github.com/gocodebox/lifterlms/blob/cdbee2b4b3bfabf3339bd6870f3d3af8e9227da0/includes/class.llms.user.permissions.php#L78 which calls `edit_others_lms_content` method

https://github.com/gocodebox/lifterlms/blob/cdbee2b4b3bfabf3339bd6870f3d3af8e9227da0/includes/class.llms.user.permissions.php#L110 which checks if the user is an instructor and passes the second argument (Object ID which ends up not being a post ID but a comment ID, see the markup above)

https://github.com/gocodebox/lifterlms/blob/41a238fd11b7c86e33bbbbc84f173ace92d26eed/includes/models/model.llms.instructor.php#L204 where we get the post type of the comment_ID which sometimes ends up being an Achievement (that's why this is so rare) and then

https://github.com/gocodebox/lifterlms/blob/41a238fd11b7c86e33bbbbc84f173ace92d26eed/includes/models/model.llms.instructor.php#L226 calls https://github.com/gocodebox/lifterlms/blob/5f48ab6d09863d8688d07dd24753c4bd8d830367/includes/llms.functions.core.php#L815 where the absence of the get method on LLMS_Achievements triggers a fatal error (https://github.com/gocodebox/lifterlms/blob/a1a6833c6e6bab57bf4356739463220e51f89408/includes/class.llms.achievement.php)

So, it seems unsafe to assume that the object ID (third parameter) will always be a post_ID and additional checks must be added to make sure that the filter isn't run on anything except posts. I'm not sure how to do that right now but logging this.

**Comment by actual-saurabh** [comment]
https://github.com/WordPress/WordPress/blob/master/wp-includes/capabilities.php#L9-L615, specifically https://github.com/WordPress/WordPress/blob/master/wp-includes/capabilities.php#L614

**Comment by thomasplevy** [comment]
`llms_get_post_parent_course()` can be very easily refactored to check the post type using wp_core_functions (like `get_post_type()` ) to check the post type can be managed by this function 

I think that solves the immediate problem.

There's a large issue as to whether `llms_get_post()` should only be allowed to be used on post types that implement the `LLMS_Post_Model()` or not. I think this requires a lot more discussion and has consequences that could affect add-ons but this particular issue can be very rapidly resolved with a quick update

**Comment by actual-saurabh** [comment]
Maybe we could use the logic of only running the filter on specific capabilities and returning early if we're not on those similar to what's done here: https://github.com/WordPress/WordPress/blob/master/wp-includes/capabilities.php#L9-L615

This could be the starting point for a more detailed capabilities functionality as per https://github.com/gocodebox/lifterlms/issues/610

**Comment by thomasplevy** [comment]
We know this is an issue but we need a bit more information to reliably recreate it in order to figure out the best way to resolve this.
